//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Plugin.rc
//
#define IDS_PLUGIN_NAME                 100
#define IDB_LOGO                        101
#define IDC_PLUGIN_ABOUT_LOGO           102
#define IDS_NAME                        128
#define IDS_VERSION_TEMPLATE            129
#define IDS_OPTIONS_TITLE               130
#define IDS_PORT_INVALID_TITLE          131
#define IDD_CASES_DLG                   132
#define IDS_PORT_INVALID_MESSAGE        133
#define IDR_TOOLBAR                     141
#define IDD_CASE_DLG                    142
#define IDD_TRIGGER_OPTS                143
#define IDD_GLOBAL_OPTS                 144
#define IDR_CASES_MENU                  145
#define IDD_RADIUS_OPTS_DLG             146
#define IDD_OPTIONS_WARNING             147
#define IDD_CAPTURE_OPTS                148
#define IDD_CASE_CAPTURE_OPTS           149
#define IDD_OPTIONS_VIEW                150
#define IDD_IMPORT_OPTS_DLG             152
#define IDD_REPLACE_CASE_DLG            153
#define IDR_CASES_TAB_MENU              154
#define IDD_VIEW_CASE                   156
#define IDD_EXPORT_OPTS_DLG             158
#define IDD_GENERAL_OPTS                202
#define IDD_USERNAME_OPTS               203
#define IDD_MODE_OPTS                   204
#define IDD_INTEGRITY_OPTS              205
#define IDD_PORT_OPTS                   206
#define IDC_BROWSE_BTN                  211
#define IDC_DISPLAY_PACKETS             214
#define IDC_LOG_MESSAGES_TO_FILE        216
#define IDC_ALLOW_POST_CAPTURE          217
#define IDD_PORT_PROP_OPTS              218
#define IDC_LOG_MESSAGES_TO_SCREEN      219
#define IDC_CAPTURE_ALL                 230
#define IDC_EDIT_USERNAME               231
#define IDC_ADD_USERNAME                232
#define IDC_DELETE_USERNAME             233
#define IDC_USERNAME_LIST               234
#define IDC_MODE_PEN                    240
#define IDC_MODE_FULL                   241
#define IDC_PEN_LABEL                   242
#define IDC_LABEL_USERNAME              250
#define IDC_ENABLE_INTEGRITY            260
#define IDC_HASH_ALG_LBL                261
#define IDC_HASH_ALG                    262
#define IDC_SIGN                        263
#define IDC_KEY_CONTAINER_LBL           264
#define IDC_KEY_CONTAINER               265
#define IDC_KEY_STATUS                  266
#define IDC_DEFAULT_CONTAINER           267
#define IDC_CREATE_KEY                  268
#define IDC_LIST                        270
#define IDC_NAME_EDIT                   271
#define IDC_DATE1                       274
#define IDC_TIME1                       275
#define IDC_DATE2                       276
#define IDC_TIME2                       277
#define IDC_EDIT_PORT                   281
#define IDC_ADD_PORT                    282
#define IDC_DELETE_PORT                 283
#define IDC_PORT_LIST                   284
#define IDC_SMTP_PORTS                  285
#define IDC_ANY_PORT                    286
#define IDC_CLEAR                       289
#define IDC_EDIT_PREFIX                 291
#define IDC_LISTBOX_PORTS               299
#define IDC_LIST_CASES                  300
#define IDC_BTN_ADD_CASE                304
#define IDC_BTN_DELETE_CASE             305
#define IDC_BTN_IMPORT_CASE             306
#define IDC_BTN_EXPORT_CASE             308
#define IDC_BTN_EDIT_CASE               309
#define IDC_BTN_COPY_CASE               310
#define IDC_PORTS                       312
#define IDC_BTN_SUGGEST_OUTPUT          313
#define IDC_EDT_MESSAGE                 318
#define IDC_OUTPUT_ROOT_EDIT            319
#define IDC_OUTPUT_ROOT_LBL             321
#define IDC_RADIUS_PORT_LBL             325
#define IDC_FILE_AGE                    326
#define IDC_FILE_SIZE                   327
#define IDC_FILE_AGE_COUNT              328
#define IDC_FILE_SIZE_COUNT             329
#define IDC_FILE_AGE_UNITS              330
#define IDC_FILE_SIZE_UNITS             331
#define IDC_BTN_SETDEFAULTS             332
#define IDC_BTN_GENERAL                 333
#define IDC_BTN_USERNAMES               334
#define IDC_BTN_TRIGGER                 335
#define IDC_CASE_NAME_DISPLAY           336
#define IDC_CAPTURE_TO_FILE             337
#define IDC_CAPTURE_TO_SCREEN           338
#define IDC_EDIT_CASE_FILEDIRECTORY     339
#define IDC_BTN_CASE_SUGGEST_OUTPUT     340
#define IDC_CASE_BROWSE_BTN             341
#define IDC_BTN_PORTS                   342
#define IDC_EDIT_PROP_PORT              343
#define IDC_ADD_PROP_PORT               344
#define IDC_DELETE_PROP_PORT            345
#define IDC_PORT_PROP_LIST              346
#define IDC_CHK_USE_GLOBAL_PORTS        347
#define IDC_CASE_CAPTURE_TO_FILE        348
#define IDC_CASE_LOG_MESSAGES_TO_FILE   349
#define IDC_CASE_CAPTURE_TO_SCREEN      350
#define IDC_BTN_CAPTURE                 351
#define IDC_CASE_LOG_MESSAGES_TO_SCREEN 352
#define IDC_CASE_FILE_AGE               353
#define IDC_CASE_FILE_SIZE              354
#define IDC_CASE_FILE_AGE_COUNT         355
#define IDC_CASE_FILE_SIZE_COUNT        356
#define IDC_CASE_FILE_AGE_UNITS         357
#define IDC_CASE_FILE_SIZE_UNITS        358
#define IDC_CHK_USE_GLOBAL_DEFAULTS     359
#define IDC_NEW_FILE_CAPTION            360
#define IDC_NEW_FILE_EVERY              361
#define IDC_BTN_MAKE_CHANGES            362
#define IDC_CHK_WARN                    363
#define IDC_CHK_DISPLAY_WARNING         364
#define IDC_BTN_OK                      365
#define IDC_CHK_USE_FILE_NUMBER         369
#define IDC_IMPORT_ENTIRE_FILE          371
#define IDC_IMPORT_CASES                372
#define IDC_CASE_LIST                   373
#define IDC_IMPORT_CASE_LIST            374
#define IDC_EDT_IMPORT_FILE             375
#define IDC_IMPORT_BROWSE               376
#define IDC_IMPORT_FILE_TEXT            377
#define ID_YES                          378
#define ID_NO                           379
#define IDC_EDT_REPLACE_MSG             380
#define IDC_CHK_ALWAYS                  381
#define IDC_EDT_HIGHLIGHT_TEXT          382
#define IDC_IMPORT_FILE_BORDER          383
#define IDC_VIEW_CASE                   384
#define IDC_BTN_READ_AND_DISPLAY        385
#define IDC_BTN_VIEW_CASE               386
#define IDC_FOLDERS_FOR_CASES           387
#define IDC_VIEW_CAPTURED_DEST          390
#define IDC_VIEW_LOG_DEST               391
#define IDC_VIEW_CASE_FOLDERS           392
#define IDC_VIEW_LOGGING_MSG            393
#define IDC_VIEW_AGE_SIZE_MSG_1         395
#define IDC_VIEW_AGE_SIZE_MSG_2         396
#define IDC_VIEW_FILE_NUMBER_MSG        398
#define IDC_VIEW_CASE_NAME              399
#define IDD_PLUGIN_ABOUT                400
#define IDC_VIEW_PREFIX                 401
#define IDC_PLUGIN_ABOUT_NAME           404
#define IDC_VIEW_OUTPUT_DIR             405
#define IDC_PLUGIN_VERSION              406
#define IDC_CONTEXT_OPTIONS_PLUGIN      407
#define IDC_CONTEXT_OPTIONS_CONTEXT     408
#define IDC_VIEW_USERNAME_LIST          409
#define IDC_EDT_EXPORT_FILE             409
#define IDD_PLUGIN_TAB                  410
#define IDC_VIEW_START_TIME             411
#define IDC_REFRESH                     412
#define IDC_VIEW_STOP_TIME              413
#define IDC_CASE_FOLDERS_FOR_CASES      414
#define IDC_MESSAGE                     415
#define IDC_CONTEXT_LIST                417
#define IDC_MAKE_CHANGES                420
#define IDD_PLUGIN_OPTIONS              1000
#define IDD_CONTEXT_TAB                 1001
#define IDS_FILE_ERROR                  1013
#define IDS_STAT_COUNT                  1014
#define ID_ADD                          40001
#define ID_EDIT                         40002
#define ID_COPY                         40003
#define ID_DELETE                       40004
#define ID_IMPORT                       40005
#define ID_EXPORT                       40006
#define ID_MENU_ADD                     40008
#define ID_MENU_EDIT                    40010
#define ID_MENU_DELETE                  40011
#define ID_MENU_ENABLEALL               40012
#define ID_MENU_DISABLEALL              40013
#define ID_CASE                         40014
#define ID_MENU_DUPLICATE               40015
#define ID_MENU_DELETEALL               40016
#define ID_MENU_VIEW                    40017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         40018
#define _APS_NEXT_CONTROL_VALUE         421
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
