//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Plugin.rc
//
#define IDS_PLUGIN_NAME                 100
#define IDR_PLUGINS                     101
#define IDB_LOGO                        101
#define IDD_PLUGIN_ABOUT                200
#define IDC_ABOUT_LOGO                  201
#define IDC_ABOUT_NAME                  202
#define IDC_PLUGIN_VERSION              203
#define IDD_PLUGIN_OPTIONS              220
#define IDC_TAB_GENERAL                 221
#define IDC_TAB_CASES                   222
#define IDC_TAB_INTEGRITY               223
#define IDC_DISPLAY_SUMMARY             242
#define IDC_DISPLAY_LOG                 243
#define IDD_CASE_LIST_OPTS              260
#define IDC_CASE_LIST                   261
#define IDC_ADD_CASE                    262
#define IDC_DELETE_CASE                 263
#define IDC_IMPORT_ADDRESS              264
#define IDC_EXPORT_ADDRESS              265
#define IDC_EDIT_CASE                   266
#define IDD_INTEGRITY_OPTS              280
#define IDC_ENABLE_INTEGRITY            281
#define IDC_HASH_ALG_LBL                282
#define IDC_HASH_ALG                    283
#define IDC_SIGN                        284
#define IDC_KEY_CONTAINER_LBL           285
#define IDC_KEY_CONTAINER               286
#define IDC_KEY_STATUS                  287
#define IDC_DEFAULT_CONTAINER           288
#define IDC_CREATE_KEY                  289
#define IDD_MODE_OPTS                   320
#define IDC_PROTOCOL_SMTP               321
#define IDC_PROTOCOL_POP3               322
#define IDC_OUTPUT_DIRECTORY            323
#define IDC_BROWSE                      324
#define IDC_MODE_PEN                    325
#define IDC_PEN_EML                     326
#define IDC_PEN_TEXT                    327
#define IDC_PEN_PER_ADDRESS             328
#define IDC_SAVE_GROUP                  329
#define IDC_SAVE_TIME                   330
#define IDC_SAVE_TIME_COUNT             331
#define IDC_SAVE_TIME_UNITS             332
#define IDC_SAVE_SIZE                   333
#define IDC_SAVE_SIZE_COUNT             334
#define IDC_SAVE_SIZE_UNITS             335
#define IDC_MODE_FULL                   336
#define IDC_FULL_EML                    337
#define IDC_FULL_PKT                    338
#define IDC_TIME_NOW                    339
#define IDC_TIME_ONE_DAY                340
#define IDC_TIME_ONE_WEEK               341
#define IDC_TIME_ONE_WEEK2              342
#define IDC_TIME_ONE_MONTH              343
#define IDD_ADDRESS_OPTS                360
#define IDC_CAPTURE_ALL                 361
#define IDC_LABEL_ADDRESS               362
#define IDC_EDIT_ADDRESS                363
#define IDC_ADD_ADDRESS                 364
#define IDC_DELETE_ADDRESS              365
#define IDC_ADDRESS_LIST                366
#define IDD_TRIGGER_OPTS                380
#define IDC_START_GROUP                 381
#define IDC_START_DATE                  382
#define IDC_START_TIME                  383
#define IDC_END_GROUP                   384
#define IDC_STOP_DATE                   385
#define IDC_STOP_TIME                   386
#define IDD_ATTACHMENT_OPTS             400
#define IDC_ATTACHMENT_SAVE             401
#define IDC_ATTACHMENT_LABEL            402
#define IDC_ATTACHMENT_DIRECTORY        403
#define IDC_ATTACHMENT_BROWSE           404
#define IDC_SLICE_STATUS                420
#define IDC_MAKE_GLOBAL                 421
#define IDC_ACCEPT_PACKETS              421
#define IDC_WRITE_PACKETS               422
#define IDC_CASE_LISTBOX                423
#define IDC_CASE_HEADER                 424
#define IDC_OPTIONS_NAVIGATE            425
#define IDC_CASE_NAME                   426
#define IDC_CASE_TREE                   427
#define IDC_CASE_VIEW                   428
#define IDC_PEN_XML                     429
#define IDC_FACILITY_LABEL              430
#define IDC_FACILITY                    431
#define IDC_LONG_NAME                   432
#define IDD_CASE_DLG                    470
#define IDD_INTEGRITY_DLG               470
#define IDC_INTEGRITY                   471
#define IDD_OPTIONS_STATUS              500
#define IDC_REFRESH                     501
#define IDD_PLUGIN_TAB                  510
#define IDC_MODIFY                      511
#define IDC_CONTEXT_LIST                512
#define IDC_CONTEXT_OPTIONS             513
#define IDD_OPTIONS_VIEW                550
#define IDD_CONTEXT_TAB                 570
#define IDS_NAME                        1001
#define IDS_VERSION_TEMPLATE            1002
#define IDS_OPTIONS_TITLE               1003
#define IDS_ADD_TARGET_TITLE            1004
#define IDS_EDIT_TARGET_TITLE           1005
#define IDS_SMTP_TOTAL                  1006
#define IDS_SMTP_FULL                   1007
#define IDS_SMTP_PEN                    1008
#define IDS_SMTP_RESET                  1009
#define IDS_SMTP_ABORT                  1010
#define IDS_SMTP_TIMEDOUT               1011
#define IDS_POP3_TOTAL                  1012
#define IDS_POP3_FULL                   1013
#define IDS_POP3_PEN                    1014
#define IDS_POP3_NO_TARGETS             1015
#define IDS_POP3_RESET                  1016
#define IDS_POP3_ABORT                  1017
#define IDS_POP3_TIMEDOUT               1018
#define IDS_FILE_ERROR                  1019
#define IDS_STAT_COUNT                  1020
#define IDS_STRING1021                  1021
#define IDS_SMTP_OPEN                   2000
#define IDS_POP3_OPEN                   2001
#define IDS_INTEGRITY_SET_DEFAULT_KEY_CONTAINER 2002
#define IDS_INTEGRITY_INVALID_INTEGRITY 2003
#define IDS_INTEGRITY_INVALID_HASH_ALG  2004
#define IDS_INTEGRITY_INVALID_SIGN_ALG  2005
#define IDS_SLICE_ON                    2100
#define IDS_SLICE_OFF                   2101
#define IDS_UNSUPPORTED_VERSION         2200
#define IDD_EMAILCAPTURE_TAB            3000
#define ID_ADD_CASE                     4000
#define IDR_TOOLBAR                     4001
#define ID_REMOVE_CASE                  4001
#define ID_IMPORT                       4002
#define ID_EXPORT                       4003
#define ID_OPTIONS                      4004
#define IDS_INTEGRITY                   4005
#define IDC_CAPTURE_LIST                5001
#define IDC_ADDRESSES_STATUS            5002
#define IDC_PROTOCOL_STATUS             5003
#define IDC_PACKETS_STATUS              5004
#define IDC_MESSAGES_STATUS             5005
#define IDC_SUMMARY_STATUS              5006
#define IDC_SAVE_STATUS                 5007
#define IDC_OUTPUT_STATUS               5008
#define IDC_NAME_STATUS                 5009
#define IDC_OUTPUT_STATUS2              5009
#define IDC_TYPE_STATUS                 5010
#define IDC_START_STATUS                5011
#define IDC_STOP_STATUS                 5012
#define IDC_FACILITY_STATUS             5013
#define IDC_CAPTURE_ALL_STATUS          5017
#define IDC_LIST1                       5018
#define IDC_FILENAME_PREFIX             5019
#define IDC_APPEND_EMAIL                5020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1000
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         5021
#define _APS_NEXT_SYMED_VALUE           600
#endif
#endif
