from setuptools import setup, find_packages

setup(
    name='OmniScript',
    version='0.6.4',
    author='LiveAction, Inc.',
    author_email='wpdn@liveaction.com',
    packages=find_packages(),
    package_data={'omniscript':
                  ['omniapi.he',
                   'Decodes/decodes.bin',
                   'libeay32.dll',
                   'libheruntime.dll',
                   'omniapi.dll',
                   'OmniScript.dll',
                   'peekutil.dll',
                   'ssleay32.dll',
                   'wpxml.dll',
                   'zlibwapi.dll',
                   'pkt2dcd.exe',
                   'Dcodu.dll',
                   'Protospecs.dll',
                   '_class_ids.txt',
                   '_co_codes.txt',
                   '_stat_ids.txt',
                   '_capture_template.xml',
                   '_capture_template_linux.xml',
                   '_capture_template_windows.xml',
                   'expertdescriptions.xml',
                   'pspecs.xml']},
    scripts=['bin/RCapture.py', 'bin/Forensics.py'],
    url='http://pypi.python.org/pypi/OmniScript/',
    license='LICENSE.txt',
    description='LiveAction Capture Engine interface module.',
    long_description=open('README.txt').read(),
    install_requires=[],
)
