/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

    THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
    KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
    PURPOSE.

Module Name:

    Public.h

Abstract:

    Header file common to app and the driver. Contains ioctl definitions
        
Environment:

     User & Kernel-mode

Revision History:


--*/

#ifdef _WIN32
#include "winioctl.h"
#endif	// _WIN32

#ifdef WP_LINUX
#define FILE_DEVICE_UNKNOWN				0x00000022

#define METHOD_BUFFERED					0
#define METHOD_IN_DIRECT				1
#define METHOD_OUT_DIRECT				2
#define METHOD_NEITHER					3

#define FILE_ANY_ACCESS					0
#define FILE_SPECIAL_ACCESS				(FILE_ANY_ACCESS)
#define FILE_READ_ACCESS				(0x0001)		// file & pipe
#define FILE_WRITE_ACCESS				(0x0002)		// file & pipe


#define CTL_CODE(DeviceType, Function, Method, Access)	(((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method))

#endif

#define	HSP_NTWK_DEVICE_TYPE						FILE_DEVICE_UNKNOWN

#define		HSP_PCIE_DEVICE_TYPE					FILE_DEVICE_UNKNOWN
#define		HSP_FUNC_BASE							0x0
#define		HSP_FUNC_TEST_MODE_RAMDISK_ENABLE		(HSP_FUNC_BASE + 0x0)
#define		HSP_FUNC_TEST_MODE_RAMDISK_DISABLE		(HSP_FUNC_BASE + 0x1)
#define		HSP_FUNC_SET_EVENT_HANDLE				(HSP_FUNC_BASE + 0x2)
#define		HSP_FUNC_RELEASE_EVENT_HANDLE			(HSP_FUNC_BASE + 0x3)
#define		HSP_FUNC_SET_EVENT						(HSP_FUNC_BASE + 0x4)
#define		HSP_FUNC_CLEAR_EVENT					(HSP_FUNC_BASE + 0x5)
#define		HSP_FUNC_CHKPY_READY_FOR_CMD			(HSP_FUNC_BASE + 0x6)
#define		HSP_FUNC_SETPX_CMD_SENT					(HSP_FUNC_BASE + 0x7)
#define		HSP_FUNC_CHKPY_RESPONSE_RDY				(HSP_FUNC_BASE + 0x8)
#define		HSP_FUNC_SETPX_ACK_RCVD					(HSP_FUNC_BASE + 0x9)
#define		HSP_FUNC_SET_MSG_COUNT					(HSP_FUNC_BASE + 0xA)
#define		HSP_FUNC_SET_READ_EVENT					(HSP_FUNC_BASE + 0xB)
#define		HSP_FUNC_CLEAR_READ_EVENT				(HSP_FUNC_BASE + 0xC)
#define		HSP_FUNC_SET_WRITE_EVENT				(HSP_FUNC_BASE + 0xD)
#define		HSP_FUNC_CLEAR_WRITE_EVENT				(HSP_FUNC_BASE + 0xE)
#define		HSP_FUNC_START_HSP10G					(HSP_FUNC_BASE + 0xF)
#define		HSP_FUNC_SET_DMA_WR_PARAMS				(HSP_FUNC_BASE + 0x10)
#define		HSP_FUNC_SET_DMA_RD_PARAMS				(HSP_FUNC_BASE + 0x11)
#define		HSP_FUNC_SET_DMA_START_RD				(HSP_FUNC_BASE + 0x12)
#define		HSP_FUNC_SET_DMA_START_WR				(HSP_FUNC_BASE + 0x13)
#define		HSP_FUNC_SETPX_MSG_CNT					(HSP_FUNC_BASE + 0x14)
#define		HSP_FUNC_STOP_HSP10G					(HSP_FUNC_BASE + 0x15)
#define		HSP_FUNC_MAP_USR_PTR					(HSP_FUNC_BASE + 0x16)
#define		HSP_FUNC_SET_FWD_DATA_EVT_NAME			(HSP_FUNC_BASE + 0x17)
#define		HSP_FUNC_CLOSE_FWD_DATA_EVT				(HSP_FUNC_BASE + 0x18)
#define		HSP_FUNC_GET_BUF_HDR_SIZE				(HSP_FUNC_BASE + 0x19)
#define		HSP_FUNC_READ_FWD_BUFFER				(HSP_FUNC_BASE + 0x1A)
#define		HSP_FUNC_GET_FWD_PARAMS					(HSP_FUNC_BASE + 0x1B)
#define		HSP_FUNC_SET_BRD_OP_MODE				(HSP_FUNC_BASE + 0x1C)
#define		HSP_FUNC_MAP_USR_STAT_PTR				(HSP_FUNC_BASE + 0x1D)
#define		HSP_FUNC_MAP_SYS_STAT_PTR				(HSP_FUNC_BASE + 0x1E)


#define		IOCTL_TEST_MODE_RAMDISK_ENABLE		CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_TEST_MODE_RAMDISK_ENABLE,	METHOD_BUFFERED, FILE_ANY_ACCESS)
#define		IOCTL_TEST_MODE_RAMDISK_DISABLE		CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_TEST_MODE_RAMDISK_DISABLE,	METHOD_BUFFERED, FILE_ANY_ACCESS)
#define		IOCTL_SET_EVENT_HANDLE				CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_SET_EVENT_HANDLE,			METHOD_BUFFERED, FILE_ANY_ACCESS)
#define		IOCTL_RELEASE_EVENT_HANDLE			CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_RELEASE_EVENT_HANDLE,		METHOD_BUFFERED, FILE_ANY_ACCESS)
#define		IOCTL_CHECK_READY_FOR_CMD			CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_CHKPY_READY_FOR_CMD,		METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define		IOCTL_SET_CMD_SENT					CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_SETPX_CMD_SENT,				METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define		IOCTL_CHECK_RESPONSE_RDY			CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_CHKPY_RESPONSE_RDY,			METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define		IOCTL_SET_ACK_RCVD					CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_SETPX_ACK_RCVD,				METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define		IOCTL_SET_MSG_COUNT					CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_SETPX_MSG_CNT,				METHOD_BUFFERED, FILE_ANY_ACCESS)
#define		IOCTL_SET_DMA_RD_PARAMS				CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_SET_DMA_RD_PARAMS,			METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define		IOCTL_START_DMA_READ_HTE			CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_SET_DMA_START_RD,			METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define		IOCTL_SET_DMA_WR_PARAMS				CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_SET_DMA_WR_PARAMS,			METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define		IOCTL_START_DMA_WRITE_ETH			CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_SET_DMA_START_WR,			METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define		IOCTL_SET_READ_EVENT				CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_SET_READ_EVENT,				METHOD_BUFFERED, FILE_ANY_ACCESS)
#define		IOCTL_CLEAR_READ_EVENT				CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_CLEAR_READ_EVENT,			METHOD_BUFFERED, FILE_ANY_ACCESS)
#define		IOCTL_SET_WRITE_EVENT				CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_SET_WRITE_EVENT,			METHOD_BUFFERED, FILE_ANY_ACCESS)
#define		IOCTL_CLEAR_WRITE_EVENT				CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_CLEAR_WRITE_EVENT,			METHOD_BUFFERED, FILE_ANY_ACCESS)
#define		IOCTL_START_HSP10G					CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_START_HSP10G,				METHOD_BUFFERED, FILE_ANY_ACCESS)
#define		IOCTL_STOP_HSP10G					CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_STOP_HSP10G,				METHOD_BUFFERED, FILE_ANY_ACCESS)
#define		IOCTL_HSPADAPTER_MAPUSR				CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_MAP_USR_PTR,				METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define		IOCTL_HSPADAPTER_SETFDEVT_NM		CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_SET_FWD_DATA_EVT_NAME,		METHOD_IN_DIRECT,  FILE_ANY_ACCESS)
#define		IOCTL_HSPADAPTER_CLOSE_FDEVT		CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_CLOSE_FWD_DATA_EVT,			METHOD_IN_DIRECT,  FILE_ANY_ACCESS)
#define		IOCTL_HSPADAPTER_GET_HDR_SZ			CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_GET_BUF_HDR_SIZE,			METHOD_OUT_DIRECT,  FILE_ANY_ACCESS)
#define		IOCTL_HSPADAPTER_READ_FWD_BUFFER	CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_READ_FWD_BUFFER,			METHOD_IN_DIRECT,  FILE_ANY_ACCESS)
#define		IOCTL_HSPADAPTER_GET_FWD_PARAMS		CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_GET_FWD_PARAMS,				METHOD_OUT_DIRECT,  FILE_ANY_ACCESS)
#define		IOCTL_HSPADAPTER_SET_OP_MODE		CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_SET_BRD_OP_MODE,			METHOD_IN_DIRECT,  FILE_ANY_ACCESS)
#define		IOCTL_HSPADAPTER_MAPSTATUSUSR		CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_MAP_USR_STAT_PTR,			METHOD_OUT_DIRECT,  FILE_ANY_ACCESS)
#define		IOCTL_HSPADAPTER_MAPSYSSTATUSUSR	CTL_CODE(HSP_PCIE_DEVICE_TYPE, HSP_FUNC_MAP_SYS_STAT_PTR,			METHOD_OUT_DIRECT,  FILE_ANY_ACCESS)
